### ISSUE TITLE
2023 VISION

### ISSUE THREAD

**Issue by pil0u** [pil0u/lewagon-aoc#232]
# The vision

The very first goal of LWxAOC is **education**. We want people to learn from each other while having fun.
In 2023, I'd rather consolidate the foundations we built and add features towards that goal.

The second goal is for contributors to have fun. Using a tech stack they love, trying the new shiny toys, it's part of the fun.

---

# Features

## The scoring system

- What scoring system in 2023?

**Feedbacks**
- Squads are good
- Randomise squads
- Weight Alumni number per year (10% * 2023 + 5% * 2022 + 2.5% * 2021 +...)
- Weight point on when the user did his Le Wagon batch
- Weight points for puzzle difficulty
- New point allocation system[0]
- Treason across cities

## Code sharing

- What vision? All by ourselves or leverage external solution? (GitHub gists)
- What features?
  - votes
  - comments

**Feedbacks**
- Mark as solved with/without external help
- Don't share solution on the same day

## Past editions & legacy

- How can we make the platform year-agnostic?
- What do we do with past data?
  - Add a `year` attribute to `Completions`

# Communication

- How to maximise participants while minimising efforts?
  - the newsletter was efficient
  - referral system?

**Feedbacks**
- Encourage pair/group programming
- Better state that LWxAOC is different from AOC
- A dedicated channel for beginners
- How-to guides to solve problems, more pedagogical resources for beginners

# Miscellaneous

**Feedbacks**
- Link AOC to Slack
  - I messaged Seb for more info
- Easter eggs (hover text on cities)
- More achievements
- Add favorite language in user settings
- Additional stats:
  - languages used
  - tagging days with difficulty
  - filter by programming language
  - personal daily score
  - graphs

[0] One (insane) idea: the total number of points per star is T=n*(n+1)/2 where n is the number of people on the leaderboard. Instead of giving n points to the faster person, then n-1 to the next, etc; give T to the first person who solve it. Then when a 2nd person solves it, review point allocation so that the 1st person gets 2/3*T and the 2nd gets 1/3*T. If k people solve the problem, the i-th person gets   (k+1-i)/(k*(k+1)/2)*T … (if all solve the problem, they get n, n-1, …, 1 point, i.e same as now).

**Comment by wJoenn** [comment]
Imo the reward system is flawed currently.
Rewarding people for something that they don't need to do themselves is an incentive to cheat.
I really like the idea you shared during our meeting at LW last week where you proposed to reward people based on contribution instead of completion. We could make a like system on the code snippets and reward the people that have the most likes. We could have theses Snippets be linked to some kind of documentation that explains how to solve the challenge either through markdown but that'll make very long snippets, or through a github README or something like that.

I do think that the conversations should be done on Slack though.
People are used to go on Slack, they will interact there anyway so trying to move the chat to the website will 1) give a poorer experience for the user because I don't think we'd end up with a better product than Slack and 2) make both chats feel emptier because the mass will never commit to the same chat.

By the way another idea for rewards but imo "most messages sent in #aoc during the event" could be another reward. Interacting is part of the event and serves education purposes too, whether is someone that explains or another that asks questions.

Finally (regarding communication 😅 ) I'm conflicted about a beginner channel because I did notice that a lot (basically all) of my classmates didn't talk on #aoc because they were kind of intimidated but tbh most students won't be doing the event anyway because they have too much in their head already. Plus creating a beginner channel would again divide the community.


Imo a Slack bot could be a nice addition, something that'll DM you when your sign up status isn't pending anymore for example, or a reminder to do a challenge, I don't know. Spamming would be a bother of course but there should be some amount of stuff we can reasonably send and that would make sense sending.
